### ISSUE TITLE
Initial Feedback

### ISSUE THREAD

**Issue by ghost** [blackwarthog/opentoonz#1]
First of all- thank you so much for this!  It is so fun to be able to draw with the MyPaint brushes in OpenToonz.

Here's some quick feedback on functionality/usability.  

Are there any plans to bring the brush settings to the UI?  Not having access to settings limits customization.  

I almost feel like the MyPaint tab and MyPaint brush settings could be its own panel that could be docked.  Right now, there is a lot of clicking back and forth between tabs to adjust color and switch brushes.

The brushes sometimes seem too big.  A brush is never able to be one pixel.  This may be a more general OpenToonz problem.

One probably crazy thought that crossed my mind is removing the standard raster brush entirely and using only MyPaint brushes.  This would eliminate some confusion for users about what type of raster brush they are using.  Another similar thought is pulling the MyPaint brush to its own tool.  

Sometimes the brush circle preview doesn't accurately represent how big the brush will be.  Example:  use the "Brush" brush at the top, set the brush size to 100.  The cursor is big but not huge, but if you draw- wow - it's huge.  This also works backwards, a brush set at one, never only draws one pixel.

Does hardness affect any MyPaint brushes?  It doesn't seem to.  That is part of why I mentioned splitting the two brushes- to remove confusion.  Opacity doesn't seem to affect all brushes also.

Again thank you for all the great work.  I am so excited to have this in OpenToonz.

**Comment by blackwarthog** [comment]
Thanks for your feedback.

Hardness have no effect for mypaint brush for now (disabled), because in current version any brush settings from OpenToonz overrides settings of original brush. For size and opacity this behavior does not making problems. But hardness usually is important part of brush pattern and with another hardness brush looks ugly.

The good solution is to change value of hardness-widget on change the brush - reset it to brush default. But for now i just ignored value of hardness widget and use only hardness from the original brush. I need some user experience to determine common workflows for the best solution for GUI.

But you still can to control hardness! I've implemented the special default-brush which tries to replicate behavior of standard OpenToonz brush using libmypaint. To enable it just select any non-mypaint brush style ('plain color' vector brush for ex.). In this mode all parameters min/max size, hardness, min/max opacity, pressure works as expected. And in this mode size of brush cursor is correct.

Brush setting configuration is huge part of MyPaint, and I do not know if it's good to implement it in OpenToonz. I'll think about it. In current version you can configure brush in original MyPaint application and use it in OpenToonz. OpenToonz can load brushes directly form MyPaint on starting.

One-pixel brush is possible. Just enabling/disabling of antialiasing not documented in libmypaint, so i need to do some research in which conditions brushes in MyPaint becomes sharp.

> Opacity doesn't seem to affect all brushes also.

It seems the "feature" of MyPaint. Can you check it in original MyPaint for this brushes?

All other artefacts seems to be bugs and should be fixed ASAP :)

**Comment by blackwarthog** [comment]
> I almost feel like the MyPaint tab and MyPaint brush settings could be its own panel that could be docked. Right now, there is a lot of clicking back and forth between tabs to adjust color and switch brushes.

Just select "Windows -> Style Editor" in menu and you will have two or more style editors (i've seen it ciople of days ago) and you may select different tabs on each. To attach dockable windows to main UI you need to drop it onto one of docks separator (it was hard for me :).

![2017-03-27 11 07 57](https://cloud.githubusercontent.com/assets/5143743/24340543/9dfb1854-12e5-11e7-81d6-b57c169a6c3d.png)

**Comment by blackwarthog** [comment]
TODO:
- [x] the brushes sometimes seem too big, and the brush circle preview doesn't accurately represent how big the brush will be;
- [x] one-pixel and sharp brushes;
- [x] <strike>allow to change hardness for MyPaint brushes and reset hardness-widget to default value on changing the brush</strike> Change GUI;
- [x] fix opacity control, currently opacity doesn't to affect all brushes;
- [x] explicitly show default-brush in list of MyPaint brushes.


And bonus :)
- [x] brush settings in the UI <strike>(i'll think about later :)</strike>. I've added only base settings of brushes without dynamics.

**Comment by blackwarthog** [comment]
Wow! Done!

I've updated appimages and windows package, and you can try again

**Comment by blackwarthog** [comment]
@turtletooth everything fixed

**Comment by morevnaproject** [comment]
@turtletooth Is it ok to close this now?

**Comment by ghost** [comment]
You bet.
