### ISSUE TITLE
Program corrupting all projects once they close

### ISSUE THREAD

**Issue by zackowens** [blackwarthog/opentoonz#3]
I am currently testing the build and every project that i transferred over is corrupted. I even did a test with a simple animation and when I closed it it was corrupted of there is a fix please let me know!

**Comment by blackwarthog** [comment]
Hello.
I cannot repeat it at windows and linux. All of my scenes saves and loads fine.

May you provide me some details, please:
- What operating system you use?
- What actions you does to reproduce the bug?
- Will be very helpfull if you can attach some example scene.

**Comment by blackwarthog** [comment]
I've tested one thing. When i save scene with MyPaint-styles in testing version of OpenToonz, then after that this scene does not opening in stable version of OpenToonz.

Scenes with MyPaint-styles cannot be loaded in stable version of OpenToonz.

If it's your case then it easy to solve. Make backup. And open changed scenes again in testing version of OpenToonz and select any non-mypaint styles for all styles where mypaint-brushes was used.

**Comment by zackowens** [comment]
How do I create a save thats not in the program?

**Comment by zackowens** [comment]
btw I use windows 10
just saving and closing reproduces the bug
I cant take a screenshot at the moment ill try

**Comment by zackowens** [comment]
should this version of testing Opentoonz have a blank page for in icon instead of the logo?

**Comment by blackwarthog** [comment]
> should this version of testing Opentoonz have a blank page for in icon instead of the logo?

Yes, i've yet not added icon into our build. I'll fix it.

**Comment by blackwarthog** [comment]
I need to understand type of corruption.

Please tell step by step in details how you opens and saves projects?
How looks the corrupted projects, what you see at screen?
Which element of OpenToonz project is corrupted, whole project, scene, level, style?

Please, attach here zip file with your test project with simple animation (about which you spoke at begin) that was corrupted.

**Comment by zackowens** [comment]
Scenes and levels are corrupting and they show up bland and red, I save and open my projects in the scene folder.
[Broken stuff.zip](https://github.com/blackwarthog/opentoonz/files/854367/Broken.stuff.zip)

I am not mad about loosing these the tools are amazing and I just want to use them without fear of killing an animation whether or not you can resolve this issue I would like to know a safe place to store files

**Comment by zackowens** [comment]
Ive done some experimenting it breaks all frames from the last save. (Ex: save 1 will be ok till save 2 is saved then save 1 breaks)

**Comment by zackowens** [comment]
also no matter where the file is saved on the computer it fries as soon is there is a raster level

**Comment by blackwarthog** [comment]
Seems i can reproduce the bug. It raises when you create ToonzRasterLayer with several frames and save it two times.

I'll try to find the source of this error.

**Comment by blackwarthog** [comment]
I've fixed that bug, thank you for your help. You may to download updated version.

Bug was fixed but it's testing version and i anyway recommend to do the backups.

**Comment by zackowens** [comment]
thank you I will retry

**Comment by zackowens** [comment]
Alright I have tried to save and open to break the frames and so far I cant thank you so much

**Comment by blackwarthog** [comment]
The problem related with wrong letter-case in file name. By the error program was replace paths and filenames to lower-case equivalents. It's have no matter while opening the file, because Windows ignoring letter-case in filenames. But using a different filenames for the same file makes undefined behaviour of OpenToons.

"Wrong" filename was written in "Open Recent Scene File" menu, you may see it. So just clear this list.

Also and more significant thing. "Wrong" names saved inside TNZ-file for level names.

I've tested only new projects and, perhaps, problem keeps for all TNZ-files affected by the bug before fix.

To fix this TNZ files you may do following:
- make backup of full all project files;
- open TNZ-file in simple text editor (notepad, for ex);
- find `<levels>` block;
- rewrite all filenames in that block to upper-case, only name - one letter, not extension, like this:
      "+drawings\\a.tlv" -> "+drawings\\A.tlv"
      "+extras\\b..tif" -> "+drawings\\B..tif"
- also you need to rename actual TIF- and TLV-files in file-system:
      a.tlv -> A.tlv
      b.0001.tif -> B.0001.tif
      b.0002.tif -> B.0002.tif

Already lost frames sadly cannot be restored :(

All projects created and edited in new version of OpenToonz should works fine.

**Comment by blackwarthog** [comment]
UPD. Seems all scenes, including edited in previous version, works and saves fine in fixed version. So my last comment have no matter.
